version: "3.9"

services:
  # 🔐 MongoDB (shared)
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  # 🧾 Auth Service
  auth-service:
    container_name: auth-service
    build: ./services/auth-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://admin:bipro@cluster0.vdort1t.mongodb.net/auth-service?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=supersecretkey
      - JWT_EXPIRES_IN=1d
    depends_on:
      - mongo
    networks:
      - backend

  